openapi: 3.0.3
info:
  title: Lumen
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/administrator/requests:
    get:
      summary: 'Wniosek o uprawnienia'
      description: ''
      parameters:
        -
          in: header
          name: api_token
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        404:
          description: Błąd
          content:
            application/json:
              schema:
                type: object
                example:
                  success: fail
                properties:
                  success:
                    type: string
                    example: fail
        201:
          description: Sukces
          content:
            application/json:
              schema:
                type: object
                example:
                  success: success
                  requests:
                    -
                      id: 1
                      user_id: 1
                      permissions: 10
                      message: test
                      accepted: '0'
                      name: 'Adrian Kowalski'
                properties:
                  success:
                    type: string
                    example: success
                  requests:
                    type: array
                    example:
                      -
                        id: 1
                        user_id: 1
                        permissions: 10
                        message: test
                        accepted: '0'
                        name: 'Adrian Kowalski'
                    items:
                      type: object
      tags:
        - Adminpanel
  /api/administrator/handleRequest:
    post:
      summary: 'Akceptuj wniosek'
      description: ''
      parameters:
        -
          in: header
          name: api_token
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        404:
          description: Błąd
          content:
            application/json:
              schema:
                type: object
                example:
                  success: fail
                properties:
                  success:
                    type: string
                    example: fail
        201:
          description: Sukces
          content:
            application/json:
              schema:
                type: object
                example:
                  success: success
                properties:
                  success:
                    type: string
                    example: success
      tags:
        - Adminpanel
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                is_accepted:
                  type: boolean
                  description: ''
                  example: false
                permission_id:
                  type: integer
                  description: ''
                  example: 13
              required:
                - is_accepted
                - permission_id
  /api/register:
    post:
      summary: Rejestracja
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        409:
          description: Błąd
          content:
            application/json:
              schema:
                type: object
                example:
                  success: fail
                properties:
                  success:
                    type: string
                    example: fail
        201:
          description: 'Użytkownik pomyślnie założony'
          content:
            application/json:
              schema:
                type: object
                example:
                  success: success
                  user:
                    name: 'Adrian Kowalski'
                    email: adrian.kowalski@gmail.com
                    updated_at: '2021-11-18T10:12:03.000000Z'
                    created_at: '2021-11-18T10:12:03.000000Z'
                    id: 4
                properties:
                  success:
                    type: string
                    example: success
                  user:
                    type: object
                    example:
                      name: 'Adrian Kowalski'
                      email: adrian.kowalski@gmail.com
                      updated_at: '2021-11-18T10:12:03.000000Z'
                      created_at: '2021-11-18T10:12:03.000000Z'
                      id: 4
      tags:
        - Autentykacja
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Nazwa użytkownika.'
                  example: 'Adrian Kowalski'
                email:
                  type: string
                  description: 'Email użytkownika.'
                  example: adrian.kowalski@gmail.com
                password:
                  type: string
                  description: 'Hasło użytkownika.'
                  example: password
                password_confirmation:
                  type: string
                  description: 'Powtórz hasło użytkownika.'
                  example: password
              required:
                - name
                - email
                - password
                - password_confirmation
      security: []
  /api/login:
    post:
      summary: Logowanie
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: Błąd
          content:
            application/json:
              schema:
                type: object
                example:
                  success: fail
                properties:
                  success:
                    type: string
                    example: fail
        201:
          description: 'Użytkownik pomyślnie zalogowany'
          content:
            application/json:
              schema:
                type: object
                example:
                  success: success
                  api_token: API_TOKEN
                  name: 'Adrian Kowalski'
                  permission: '1'
                properties:
                  success:
                    type: string
                    example: success
                  api_token:
                    type: string
                    example: API_TOKEN
                  name:
                    type: string
                    example: 'Adrian Kowalski'
                  permission:
                    type: string
                    example: '1'
      tags:
        - Autentykacja
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Email użytkownika.'
                  example: adrian.kowalski@gmail.com
                password:
                  type: string
                  description: 'Hasło użytkownika.'
                  example: password
              required:
                - email
                - password
      security: []
  /api/logout:
    post:
      summary: Wylogowanie
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        403:
          description: Błąd
          content:
            application/json:
              schema:
                type: object
                example:
                  success: fail
                properties:
                  success:
                    type: string
                    example: fail
        201:
          description: 'Pomyślnie wylogowano'
          content:
            application/json:
              schema:
                type: object
                example:
                  success: success
                properties:
                  success:
                    type: string
                    example: success
      tags:
        - Autentykacja
      security: []
  /api/supplier/add:
    post:
      summary: 'Dodaj szczepionki'
      description: ''
      parameters:
        -
          in: header
          name: api_token
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        404:
          description: Błąd
          content:
            application/json:
              schema:
                type: object
                example:
                  success: fail
                properties:
                  success:
                    type: string
                    example: fail
        201:
          description: Sukces
          content:
            application/json:
              schema:
                type: object
                example:
                  success: success
                properties:
                  success:
                    type: string
                    example: success
      tags:
        - Dostawca
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                count:
                  type: integer
                  description: ''
                  example: 11
              required:
                - count
  /api/courier/couriers:
    get:
      summary: 'Pobierz listę kurierów'
      description: ''
      parameters:
        -
          in: header
          name: api_token
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        201:
          description: Sukces
          content:
            application/json:
              schema:
                type: object
                example:
                  success: success
                  couriers:
                    -
                      courier_id: 1
                      name: DHL
                properties:
                  success:
                    type: string
                    example: success
                  couriers:
                    type: array
                    example:
                      -
                        courier_id: 1
                        name: DHL
                    items:
                      type: object
      tags:
        - Kurier
  /api/hospitalWorker/patientsCount:
    get:
      summary: 'Pobierz ilość pacjentów'
      description: ''
      parameters:
        -
          in: header
          name: api_token
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        201:
          description: Sukces
          content:
            application/json:
              schema:
                type: object
                example:
                  success: success
                  count: 10
                properties:
                  success:
                    type: string
                    example: success
                  count:
                    type: integer
                    example: 10
      tags:
        - 'Pracownik szpitala'
    post:
      summary: 'Zmień ilość pacjentów'
      description: ''
      parameters:
        -
          in: header
          name: api_token
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        201:
          description: Sukces
          content:
            application/json:
              schema:
                type: object
                example:
                  success: success
                properties:
                  success:
                    type: string
                    example: success
      tags:
        - 'Pracownik szpitala'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                count:
                  type: integer
                  description: ''
                  example: 3
              required:
                - count
  /api/hospitalWorker/hospitalWorkers:
    get:
      summary: 'Pobierz listę pracowników szpitali'
      description: ''
      parameters:
        -
          in: header
          name: api_token
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        201:
          description: Sukces
          content:
            application/json:
              schema:
                type: object
                example:
                  success: success
                  hospital_workers:
                    -
                      hospital_worker_id: 1
                      name: 'Szczepan Nowak'
                properties:
                  success:
                    type: string
                    example: success
                  hospital_workers:
                    type: array
                    example:
                      -
                        hospital_worker_id: 1
                        name: 'Szczepan Nowak'
                    items:
                      type: object
      tags:
        - 'Pracownik szpitala'
  /api/hospitalWorker/requestSupply:
    post:
      summary: 'Złóż zapotrzebowanie na szczepionki'
      description: ''
      parameters:
        -
          in: header
          name: api_token
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        201:
          description: Sukces
          content:
            application/json:
              schema:
                type: object
                example:
                  success: success
                properties:
                  success:
                    type: string
                    example: success
      tags:
        - 'Pracownik szpitala'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                vaccine_count:
                  type: integer
                  description: ''
                  example: 16
              required:
                - vaccine_count
  /api/requestPermission:
    post:
      summary: 'Wniosek o uprawnienia'
      description: ''
      parameters:
        -
          in: header
          name: api_token
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        404:
          description: Błąd
          content:
            application/json:
              schema:
                type: object
                example:
                  success: fail
                properties:
                  success:
                    type: string
                    example: fail
        201:
          description: 'Użytkownik pomyślnie założony'
          content:
            application/json:
              schema:
                type: object
                example:
                  success: success
                properties:
                  success:
                    type: string
                    example: success
      tags:
        - Różne
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                permission:
                  type: integer
                  description: ''
                  example: 1
                message:
                  type: string
                  description: 'Opcjonalna wiadomość.'
                  example: Wiadomość
              required:
                - permission
  /api/common/transfer:
    post:
      summary: 'Wykonaj transfer szczepionek do innego użytkownika'
      description: ''
      parameters:
        -
          in: header
          name: api_token
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        404:
          description: Błąd
          content:
            application/json:
              schema:
                type: object
                example:
                  success: fail
                properties:
                  success:
                    type: string
                    example: fail
        201:
          description: Sukces
          content:
            application/json:
              schema:
                type: object
                example:
                  success: success
                properties:
                  success:
                    type: string
                    example: success
      tags:
        - Różne
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: ''
                  example: 6
                count:
                  type: integer
                  description: ''
                  example: 10
              required:
                - user_id
                - count
tags:
  -
    name: Adminpanel
    description: "\nPanel administratora"
  -
    name: Autentykacja
    description: "\nEndpointy do rejestracji i logowania"
  -
    name: Dostawca
    description: ''
  -
    name: Kurier
    description: ''
  -
    name: 'Pracownik szpitala'
    description: "\nEndpointy do rejestracji i logowania"
  -
    name: Różne
    description: ''
components:
  securitySchemes:
    default:
      type: apiKey
      name: api_token
      in: header
      description: ''
security:
  -
    default: []
